[package]
name = "demo_room"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
cimvr_common = { git = "https://github.com/ChatImproVR/iteration0.git", branch = "main" }
cimvr_engine_interface  = { git = "https://github.com/ChatImproVR/iteration0.git", branch = "main" }
obj_parser = { git = "https://github.com/ChatImproVR/iteration0.git", branch = "obj_parser" }
serde = { version = "1", features = ["derive"] }
